### ISSUE TITLE
Translate queries page

### ISSUE THREAD

**Issue by petehouston** [petehouston/laravel-docs-vn#38]
Source: https://github.com/laravel/docs/blob/5.2/queries.md

**Comment by bangnokia** [comment]
i will translate this page

**Comment by petehouston** [comment]
@bangnokia how's the progress so far bro?

**Comment by bangnokia** [comment]
@petehouston  i'm sorry, my hands  have some problem

**Comment by petehouston** [comment]
Added via https://github.com/petehouston/laravel-docs-vn/pull/69

@bangnokia thanks bro.
