### ISSUE TITLE
Translate quickstart page

### ISSUE THREAD

**Issue by petehouston** [petehouston/laravel-docs-vn#41]
Source: https://github.com/laravel/docs/blob/5.2/quickstart.md

**Comment by dinhquochan** [comment]
Translating

**Comment by petehouston** [comment]
how's the progress so far, bro @dinhquochan ?

**Comment by dinhquochan** [comment]
Em xin lỗi nhé, bữa rài đang dịch cái bận tí em hoàn thành 😊

**Comment by petehouston** [comment]
Added via https://github.com/petehouston/laravel-docs-vn/pull/68
