### ISSUE TITLE
Translate structure page

### ISSUE THREAD

**Issue by petehouston** [petehouston/laravel-docs-vn#49]
Source: https://github.com/laravel/docs/blob/5.2/structure.md

**Comment by nhathm** [comment]
đang dịch bài này

**Comment by petehouston** [comment]
bài này xong chưa @RioV ? PR lên đi

**Comment by nhathm** [comment]
em commit lên brach của em rồi, phải làm gì nữa không a?

**Comment by petehouston** [comment]
em fork về tài khoản github của em, tiến hành chỉnh sửa trên repo đó, commit hết lên. rồi ấn vào cái nút Pull Request trên repo của em, điền thông tin tiếp là được.

**Comment by petehouston** [comment]
Closed via https://github.com/petehouston/laravel-docs-vn/pull/58
