### ISSUE TITLE
Translate collection page

### ISSUE THREAD

**Issue by petehouston** [petehouston/laravel-docs-vn#6]
Source: https://github.com/laravel/docs/blob/5.2/collections.md

**Comment by bangnokia** [comment]
translating this

**Comment by bangnokia** [comment]
link source có vấn đề khi hiển thị trong markdown

**Comment by petehouston** [comment]
Không sao em nhé, vì bộ docs này sẽ được build thành web tra cứu như trên [laravel.com](https://laravel.com/docs/5.2/collections), vì thế, em cứ dịch như nguyên bản.

<img width="1099" alt="screen shot 2016-06-07 at 09 51 40" src="https://cloud.githubusercontent.com/assets/9006720/15844567/98ef83b8-2c95-11e6-81af-dc74ca8d0ddb.png">

<img width="1128" alt="screen shot 2016-06-07 at 09 51 51" src="https://cloud.githubusercontent.com/assets/9006720/15844566/98eba66c-2c95-11e6-995a-7053748ca6ea.png">

**Comment by petehouston** [comment]
Added via https://github.com/petehouston/laravel-docs-vn/pull/65
